# opkg configuration for EE71
# Local feed on /cache, packages install to /
src/gz ee71 file:///cache/opkg

dest root /
lists_dir ext /usr/lib/opkg/lists
option tmp_dir /tmp
option overlay_root /cache

arch all 100
arch armv7 200
arch armv7-softfp 300
